from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from accounts.permissions import IsRecruiter, IsStudent
from jobs.models import Job

from .models import Application
from .serializers import ApplicationSerializer


class ApplicationViewSet(viewsets.ModelViewSet):
    """
    CRUD for applications + custom pipeline actions.

    Endpoints (auto-generated by the router):
        GET    /api/applications/              -> list (student: own; recruiter: for their jobs)
        POST   /api/applications/              -> apply to a job (student only)
        GET    /api/applications/:id/          -> detail
        DELETE /api/applications/:id/          -> withdraw (student, own only)
        PATCH  /api/applications/:id/status/   -> recruiter updates status
        GET    /api/applications/job/:job_id/  -> recruiter lists applicants for one job
    """

    serializer_class = ApplicationSerializer

    def get_queryset(self):
        """
        Filter the queryset by role so a student never sees another student's
        applications, and a recruiter never sees applications to other jobs.

        select_related avoids the N+1 problem when serializing related users/jobs.
        """
        user = self.request.user

        if user.role == "student":
            return (
                Application.objects
                .filter(student=user)
                .select_related("job", "job__recruiter", "job__recruiter__recruiter_profile")
            )

        if user.role == "recruiter":
            return (
                Application.objects
                .filter(job__recruiter=user)
                .select_related("student", "job")
            )

        # Admins and anyone else: nothing for now.
        return Application.objects.none()

    def get_permissions(self):
        """
        Choose permission classes based on which action is running.
        More specific than a single class because different actions
        are open to different roles.
        """
        if self.action == "create":
            # Only students can apply.
            return [IsAuthenticated(), IsStudent()]
        if self.action == "destroy":
            # Only students can withdraw.
            return [IsAuthenticated(), IsStudent()]
        if self.action in ("update_status", "list_applicants"):
            # Only recruiters can view/act on applicants.
            return [IsAuthenticated(), IsRecruiter()]
        # list, retrieve -> any authenticated user (queryset already scoped).
        return [IsAuthenticated()]

    def perform_create(self, serializer):
        """
        Attach the student and a resume snapshot.
        Clients can't set these because they're read-only on the serializer.
        """
        profile = self.request.user.student_profile
        serializer.save(
            student=self.request.user,
            resume=profile.resume,   # snapshot the current resume
        )

    def destroy(self, request, *args, **kwargs):
        """
        Withdraw an application.
        The queryset already restricts students to their own applications,
        but we double-check here for clarity and safety.
        """
        instance = self.get_object()
        if instance.student != request.user:
            return Response(
                {"detail": "You can only withdraw your own applications."},
                status=status.HTTP_403_FORBIDDEN,
            )
        return super().destroy(request, *args, **kwargs)

    # ------------------------------------------------------------------
    # Custom actions
    # ------------------------------------------------------------------

    @action(detail=True, methods=["patch"], url_path="status")
    def update_status(self, request, pk=None):
        """
        PATCH /api/applications/:id/status/
        Recruiter moves an applicant to the next stage.

        Body: { "status": "shortlisted" }
        """
        application = self.get_object()

        # Object-level check: recruiter must own the job.
        if application.job.recruiter != request.user:
            return Response(
                {"detail": "You can only update applications for your own jobs."},
                status=status.HTTP_403_FORBIDDEN,
            )

        new_status = request.data.get("status")

        # Validate against the enum, not just any string.
        valid_statuses = [choice[0] for choice in Application.Status.choices]
        if new_status not in valid_statuses:
            return Response(
                {"detail": f"Invalid status. Choose one of: {', '.join(valid_statuses)}."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        application.status = new_status
        application.save(update_fields=["status", "updated_at"])

        return Response(ApplicationSerializer(application).data)

    @action(detail=False, methods=["get"], url_path=r"job/(?P<job_id>\d+)")
    def list_applicants(self, request, job_id=None):
        """
        GET /api/applications/job/:job_id/
        Recruiter sees all applications for one of their jobs.
        """
        # Confirm the job exists AND belongs to this recruiter.
        try:
            job = Job.objects.get(pk=job_id, recruiter=request.user)
        except Job.DoesNotExist:
            return Response(
                {"detail": "Job not found, or it does not belong to you."},
                status=status.HTTP_404_NOT_FOUND,
            )

        applications = (
            Application.objects
            .filter(job=job)
            .select_related("student")
            .order_by("-applied_at")
        )

        # Respect pagination if configured.
        page = self.paginate_queryset(applications)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(applications, many=True)
        return Response(serializer.data)